---
configs:
    select: 'test1'
    test1:
      public_ip: '192.168.1.11'
      cpu_int: 2
      memory_int: 2048
      ethernet_string: "ens192"
      defualt_driver_string: "qemu"
    test2:
      public_ip: '192.168.2.22'
      cpu_int: 2
      memory_int: 2048
      defualt_driver_string: "kvm"
      ethernet_string: "ens192"

## Create a template for the generation of the vagrantfile
## Use ansible facts for ethernet
## May want to add the ansible_user and ansible remote pass to this as well...