# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

# Load Dynamic Vars from Yaml File
current_dir    = File.dirname(File.expand_path(__FILE__))
configs        = YAML.load_file("#{current_dir}/config.yaml")
vagrant_config = configs['configs'][configs['configs']['select']]

Vagrant.configure('2') do |config|

    box_name == vagrant_config['base_box']
    config.vm.box = "file://boxes/"+( box_name )
    config.vm.synced_folder ".", "/vagrant", disable: true
    
    config.vm.provider :libvirt do |libvirt|
      libvirt.cpus = vagrant_config['cpu_int']
      libvirt.memory = vagrant_config['memory_int']
      libvirt.nested = true
      libvirt.driver = vagrant_config['default_driver_string']
    end

    # Shell provisioning
    config.vm.provision "shell", inline: <<-SHELL
      echo "Shell Provisioner"
    SHELL
  end
end
