# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

# Load Dynamic Vars from Yaml File
current_dir    = File.dirname(File.expand_path(__FILE__))
configs        = YAML.load_file("#{current_dir}/config.yaml")
vagrant_config = configs['configs'][configs['configs']['select']]
box_name       = vagrant_config['base_box']

Vagrant.configure('2') do |config|
    config.vm.box = "file://boxes/libvirt-"+( box_name )
    config.ssh.username = "root"
    config.ssh.password = "testtest"
    config.vm.provider :libvirt do |libvirt|
      libvirt.cpus = vagrant_config['cpu']
      libvirt.memory = vagrant_config['memory']
      libvirt.nested = true
      libvirt.driver = "qemu" # Default 1
      libvirt.driver = "kvm"  # Default 2 
      libvirt.driver = vagrant_config['driver'] # import var and use if available
    end

    # Shell provisioning
    config.vm.provision "shell", inline: <<-SHELL
      echo "Shell Provisioner"
    SHELL

    end

